2021-12-04 08:23:52,431: WARNING: urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=55846): Max retries exceeded with url: /session/4ea1f7097a70c44a2283ea409b8f4f15/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x044C1928>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。')) [autorun_manager/app.py][line:220]

Traceback (most recent call last):
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1006, in _send_output
    self.send(msg)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 946, in send
    self.connect()
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x044C1928>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 220, in <module>
    run_all_apps(app_dict,mode='debug')
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 80, in _decoration_func
    raise e
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 76, in _decoration_func
    return func(*args, **kwargs)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 157, in run_all_apps
    run_app(key)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 80, in _decoration_func
    raise e
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 76, in _decoration_func
    return func(*args, **kwargs)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 167, in run_app
    result_text = app.run()
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\auto_mail_check\app.py", line 113, in run
    es.get('https://webmail.jikei.ac.jp/',sleeptime=5)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easyselenium.py", line 56, in get
    self.driver.get(url)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\kizuk\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=55846): Max retries exceeded with url: /session/4ea1f7097a70c44a2283ea409b8f4f15/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x044C1928>: Failed to establish a new connection: [WinError 10061] 対象のコンピューターによって拒否されたため、接続できませんでした。'))

2021-12-04 08:29:06,505: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:29:06,626: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:29:06,626: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:29:06,627: INFO: ---------- start add_newapps() ----------
2021-12-04 08:29:06,630: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:29:06,634: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:29:06,638: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:29:06,646: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:29:06,648: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:29:06,648: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:29:06,648: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:29:06,655: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:29:06,656: INFO: ---------- end add_newapps() ----------
2021-12-04 08:29:06,656: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:29:06,658: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:29:06,658: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:29:06,679: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:29:06,680: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:29:06,681: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:30:05,700: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:30:05,701: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:30:05,701: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:30:46,540: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:30:46,650: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:30:46,650: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:30:46,651: INFO: ---------- start add_newapps() ----------
2021-12-04 08:30:46,654: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:30:46,658: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:30:46,661: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:30:46,669: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:30:46,671: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:30:46,671: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:30:46,671: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:30:46,678: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:30:46,680: INFO: ---------- end add_newapps() ----------
2021-12-04 08:30:46,680: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:30:46,681: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:30:46,681: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:30:46,692: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:30:46,693: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:30:46,694: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:31:43,554: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:31:43,557: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:31:43,557: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:34:38,635: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:34:38,704: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:34:38,704: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:34:38,704: INFO: ---------- start add_newapps() ----------
2021-12-04 08:34:38,707: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:34:38,709: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:34:38,711: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:34:38,716: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:34:38,717: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:34:38,717: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:34:38,717: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:34:38,718: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:34:38,719: INFO: ---------- end add_newapps() ----------
2021-12-04 08:34:38,719: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:34:38,720: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:34:38,720: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:39:25,003: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:39:25,072: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:39:25,072: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:39:25,072: INFO: ---------- start add_newapps() ----------
2021-12-04 08:39:25,074: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:39:25,077: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:39:25,080: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:39:25,085: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:39:25,086: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:39:25,086: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:39:25,087: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:39:25,088: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:39:25,089: INFO: ---------- end add_newapps() ----------
2021-12-04 08:39:25,089: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:39:25,089: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:39:25,090: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:39:25,090: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:39:25,091: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:39:25,091: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:40:40,968: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:40:40,969: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:40:40,970: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:43:59,124: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:43:59,126: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:43:59,127: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:44:24,814: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:44:24,882: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:44:24,882: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:44:24,882: INFO: ---------- start add_newapps() ----------
2021-12-04 08:44:24,885: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:44:24,888: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:44:24,891: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:44:24,897: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:44:24,899: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:44:24,899: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:44:24,899: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:44:24,901: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:44:24,903: INFO: ---------- end add_newapps() ----------
2021-12-04 08:44:24,903: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:44:24,903: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:44:24,904: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:44:24,912: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:44:24,913: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:44:24,913: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:48:10,829: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 08:48:10,900: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:48:10,900: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:48:10,900: INFO: ---------- start add_newapps() ----------
2021-12-04 08:48:10,902: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:48:10,905: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 08:48:10,907: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 08:48:10,913: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 08:48:10,914: INFO: [実行元]autorun_manager/app.py 219行目 <module>
2021-12-04 08:48:10,915: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:48:10,915: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 08:48:10,916: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 08:48:10,917: INFO: ---------- end add_newapps() ----------
2021-12-04 08:48:10,917: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 08:48:10,918: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:48:10,918: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 08:48:10,919: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:48:10,920: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:48:10,920: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:51:19,366: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:51:19,368: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:51:19,368: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 08:52:05,138: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 08:52:05,142: INFO: [実行元]autorun_manager/app.py 220行目 <module>
2021-12-04 08:52:05,142: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:03:22,722: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 09:03:22,791: INFO: [実行元]autorun_manager/app.py 223行目 <module>
2021-12-04 09:03:22,791: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 09:03:22,791: INFO: ---------- start add_newapps() ----------
2021-12-04 09:03:22,794: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:03:22,796: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 09:03:22,798: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:03:22,803: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 09:03:22,804: INFO: [実行元]autorun_manager/app.py 223行目 <module>
2021-12-04 09:03:22,804: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:03:22,804: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 09:03:22,805: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 09:03:22,806: INFO: ---------- end add_newapps() ----------
2021-12-04 09:03:22,806: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 09:03:22,807: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:03:22,807: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 09:03:22,813: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 09:03:22,814: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:03:22,814: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:03:24,484: ERROR: NameError: name 'key' is not defined [modules/easylogger.py][line:76]

Traceback (most recent call last):
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 76, in _decoration_func
    return func(*args, **kwargs)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 170, in run_app
    el.info('実行：{}'.format(key))
NameError: name 'key' is not defined

2021-12-04 09:03:24,485: ERROR: NameError: name 'key' is not defined [autorun_manager/app.py][line:147]

Traceback (most recent call last):
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 147, in run_all_apps
    run_app(key)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 80, in _decoration_func
    raise e
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py", line 76, in _decoration_func
    return func(*args, **kwargs)
  File "C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py", line 170, in run_app
    el.info('実行：{}'.format(key))
NameError: name 'key' is not defined

2021-12-04 09:08:23,923: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 09:08:23,992: INFO: [実行元]autorun_manager/app.py 223行目 <module>
2021-12-04 09:08:23,992: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 09:08:23,992: INFO: ---------- start add_newapps() ----------
2021-12-04 09:08:23,996: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:08:23,998: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 09:08:24,001: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:08:24,005: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 09:08:24,006: INFO: [実行元]autorun_manager/app.py 223行目 <module>
2021-12-04 09:08:24,006: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:08:24,006: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 09:08:24,008: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 09:08:24,009: INFO: ---------- end add_newapps() ----------
2021-12-04 09:08:24,009: INFO: ---------- 関数.run_all_apps 実行 ----------
2021-12-04 09:08:24,010: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:08:24,010: INFO: [実行元]modules/easylogger.py 72行目 _decoration_func
2021-12-04 09:08:24,010: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 09:08:24,012: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:08:24,012: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:08:25,524: INFO: 実行：auto_bt_check.py
2021-12-04 09:09:27,030: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 09:09:27,033: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:09:27,034: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:09:28,335: INFO: 実行：auto_mail_check.py
2021-12-04 09:10:28,975: INFO: ---------- 関数.run_app 実行 ----------
2021-12-04 09:10:28,976: INFO: [実行元]autorun_manager/app.py 224行目 <module>
2021-12-04 09:10:28,977: INFO: [実行元]modules/easylogger.py 76行目 _decoration_func
2021-12-04 09:10:30,243: INFO: 実行：auto_manga_check.py
2021-12-04 09:50:52,142: INFO: ---------- 関数.pop_all_autorun_log 実行 ----------
2021-12-04 09:50:52,215: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py 222行目 <module>
2021-12-04 09:50:52,216: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py 72行目 _decoration_func
2021-12-04 09:50:52,217: INFO: autorun_manager_logを空にしました。
2021-12-04 09:50:52,217: INFO: ---------- 関数.check_all_apps_status 実行 ----------
2021-12-04 09:50:52,217: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py 223行目 <module>
2021-12-04 09:50:52,218: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py 72行目 _decoration_func
2021-12-04 09:50:52,218: INFO: ---------- start add_newapps() ----------
2021-12-04 09:50:52,222: INFO:     [auto_bt_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:50:52,224: INFO:     [auto_mail_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 3
2021-12-04 09:50:52,226: INFO:     [auto_manga_check/settings.py]APP_FOR_AUTO_RUN = True, RUN_FREQUENCY = 1
2021-12-04 09:50:52,232: INFO: ---------- 関数.get_autorun_app_list 実行 ----------
2021-12-04 09:50:52,233: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\app.py 223行目 <module>
2021-12-04 09:50:52,233: INFO: [実行元]C:\Users\kizuk\Desktop\git\python-garage\autorun_manager\..\modules\easylogger.py 76行目 _decoration_func
2021-12-04 09:50:52,233: INFO: ---------- start get_autorun_app_list() ----------
2021-12-04 09:50:52,234: INFO: ---------- end get_autorun_app_list() ----------
2021-12-04 09:50:52,235: INFO: ---------- end add_newapps() ----------
